name: imgts
channels:
  - pytorch
  - conda-forge

dependencies:
  - python
  - numpy
  - opencv
  - pytorch
  - torchvision
  - pillow
  - pandas
  - pip
  - fsspec
  - gcfs
  - aiohttp
  - requests
